name = "w88y"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "101874e82d3ff354e72f3ff4e5894de2"
workers_dev = false
routes = [
#{ pattern = "11lou11.com/*", zone_name = "11lou11.com" },
#{ pattern = "2emg.com/*", zone_name = "2emg.com" },
#{ pattern = "2vbr.com/*", zone_name = "2vbr.com" },
#{ pattern = "3iwf.com/*", zone_name = "3iwf.com" },
#{ pattern = "43xo6r.com/*", zone_name = "43xo6r.com" },
#{ pattern = "4opd.com/*", zone_name = "4opd.com" },
#{ pattern = "51bqvje.com/*", zone_name = "51bqvje.com" },
#{ pattern = "51dil.com/*", zone_name = "51dil.com" },
#{ pattern = "51nyvtd.com/*", zone_name = "51nyvtd.com" },
#{ pattern = "51opaxk.com/*", zone_name = "51opaxk.com" },
#{ pattern = "51rfk.com/*", zone_name = "51rfk.com" },
#{ pattern = "51uivoq.com/*", zone_name = "51uivoq.com" },
#{ pattern = "52lsz.com/*", zone_name = "52lsz.com" },
#{ pattern = "52nol.com/*", zone_name = "52nol.com" },
#{ pattern = "52pgomk.com/*", zone_name = "52pgomk.com" },
#{ pattern = "52uji.com/*", zone_name = "52uji.com" },
#{ pattern = "52vcp.com/*", zone_name = "52vcp.com" },
#{ pattern = "5jiv.com/*", zone_name = "5jiv.com" },
#{ pattern = "6kd2me.com/*", zone_name = "6kd2me.com" },
#{ pattern = "88ebh.com/*", zone_name = "88ebh.com" },
#{ pattern = "88flc.com/*", zone_name = "88flc.com" },
#{ pattern = "88prq.com/*", zone_name = "88prq.com" },
#{ pattern = "88ypm.com/*", zone_name = "88ypm.com" },
#{ pattern = "94y2ul.com/*", zone_name = "94y2ul.com" },
#{ pattern = "caa88yo.com/*", zone_name = "caa88yo.com" },
#{ pattern = "cauts.com/*", zone_name = "cauts.com" },
#{ pattern = "crrcgcx.cc/*", zone_name = "crrcgcx.cc" },
#{ pattern = "e6sgj.com/*", zone_name = "e6sgj.com" },
#{ pattern = "ewiot88.com/*", zone_name = "ewiot88.com" },
#{ pattern = "ggmux.com/*", zone_name = "ggmux.com" },
#{ pattern = "gkewn.com/*", zone_name = "gkewn.com" },
#{ pattern = "hijqk.com/*", zone_name = "hijqk.com" },
#{ pattern = "l52yahv.com/*", zone_name = "l52yahv.com" },
#{ pattern = "lotqf.com/*", zone_name = "lotqf.com" },
#{ pattern = "lqrbi.com/*", zone_name = "lqrbi.com" },
#{ pattern = "mbxqd.com/*", zone_name = "mbxqd.com" },
#{ pattern = "n46c.com/*", zone_name = "n46c.com" },
#{ pattern = "nirtv.com/*", zone_name = "nirtv.com" },
#{ pattern = "nwdmr.com/*", zone_name = "nwdmr.com" },
#{ pattern = "otqyr.com/*", zone_name = "otqyr.com" },
#{ pattern = "pawhf.com/*", zone_name = "pawhf.com" },
#{ pattern = "ph8yxp.com/*", zone_name = "ph8yxp.com" },
#{ pattern = "produce-partner.com/*", zone_name = "produce-partner.com" },
#{ pattern = "qpjnt.com/*", zone_name = "qpjnt.com" },
#{ pattern = "rfxwv.com/*", zone_name = "rfxwv.com" },
#{ pattern = "rhucx.com/*", zone_name = "rhucx.com" },
#{ pattern = "rxvor.com/*", zone_name = "rxvor.com" },
#{ pattern = "services-sciences.org/*", zone_name = "services-sciences.org" },
#{ pattern = "uuvgq.com/*", zone_name = "uuvgq.com" },
#{ pattern = "vdovv.com/*", zone_name = "vdovv.com" },
#{ pattern = "vk8nlm.com/*", zone_name = "vk8nlm.com" },
#{ pattern = "vknlm.com/*", zone_name = "vknlm.com" },
#{ pattern = "w88azng.com/*", zone_name = "w88azng.com" },
#{ pattern = "wuydv.com/*", zone_name = "wuydv.com" },
#{ pattern = "ycvfu.com/*", zone_name = "ycvfu.com" },
#{ pattern = "yxcfr.com/*", zone_name = "yxcfr.com" },
#{ pattern = "z20hx.com/*", zone_name = "z20hx.com" }

]