name = "12bet"
main = "./worker.js"
compatibility_date = "2023-24-10"

account_id = "16955a31f332cc9cc356f745dc53a078"
workers_dev = false
route = { pattern = "nnaoxiang.com/*", zone_name = "nnaoxiang.com" }