name = "fun88"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
route = { pattern = "0598jzw.com/*", zone_name = "0598jzw.com" }
route = { pattern = "battleofbeaverdams.com/*", zone_name = "battleofbeaverdams.com" }
route = { pattern = "becomeacroatiafan.com/*", zone_name = "becomeacroatiafan.com" }
route = { pattern = "clb-sx.com/*", zone_name = "clb-sx.com" }
route = { pattern = "clementine-baron.com/*", zone_name = "clementine-baron.com" }
route = { pattern = "dgmcsy.com/*", zone_name = "dgmcsy.com" }
route = { pattern = "fjltsn.com/*", zone_name = "fjltsn.com" }
route = { pattern = "www.htysw.net/*", zone_name = "htysw.net" }
route = { pattern = "www.huiwenbio.com/*", zone_name = "huiwenbio.com" }
route = { pattern = "jiankang8090.com/*", zone_name = "jiankang8090.com" }
route = { pattern = "jincisj.com/*", zone_name = "jincisj.com" }
route = { pattern = "www.jxtrans.net/*", zone_name = "jxtrans.net" }
route = { pattern = "lacocinadejuanry.com/*", zone_name = "lacocinadejuanry.com" }
route = { pattern = "www.minrongshiye.com/*", zone_name = "minrongshiye.com" }
route = { pattern = "www.qinanjidian.com/*", zone_name = "qinanjidian.com" }
route = { pattern = "www.sanyayc.com/*", zone_name = "sanyayc.com" }
route = { pattern = "www.sdqzlongxin.com/*", zone_name = "sdqzlongxin.com" }
route = { pattern = "shujy.com/*", zone_name = "shujy.com" }
route = { pattern = "szzxdch.com/*", zone_name = "szzxdch.com" }
route = { pattern = "www.xaylssgs.com/*", zone_name = "xaylssgs.com" }
route = { pattern = "www.ynhlmgdl.com/*", zone_name = "ynhlmgdl.com" }
route = { pattern = "www.zbchangda.com/*", zone_name = "zbchangda.com" }
route = { pattern = "www.zfdwz.com/*", zone_name = "zfdwz.com" }
