name = "multiy"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "101874e82d3ff354e72f3ff4e5894de2"
workers_dev = false
[placement]
mode = "smart"
routes = [
{ pattern = "eszvn.com/*", zone_name = "eszvn.com" },
{ pattern = "lsp2.com/*", zone_name = "lsp2.com" },
{ pattern = "ompvh.com/*", zone_name = "ompvh.com" },
{ pattern = "rori.tv/*", zone_name = "rori.tv" },
{ pattern = "ughbj.com/*", zone_name = "ughbj.com" },
{ pattern = "vztug.com/*", zone_name = "vztug.com" },
{ pattern = "cloudream.name/*", zone_name = "cloudream.name" },
{ pattern = "dwsrh.com/*", zone_name = "dwsrh.com" },
{ pattern = "h8mjq.com/*", zone_name = "h8mjq.com" },
{ pattern = "sunoano.name/*", zone_name = "sunoano.name" },
{ pattern = "universal-interop-council.org/*", zone_name = "universal-interop-council.org" },
{ pattern = "zgyouwan.com/*", zone_name = "zgyouwan.com" },
{ pattern = "jftyjsqc.com/*", zone_name = "jftyjsqc.com" },
{ pattern = "ftox8b.com/*", zone_name = "ftox8b.com" },
{ pattern = "01mbhn.com/*", zone_name = "01mbhn.com" },
{ pattern = "11ckfu.com/*", zone_name = "11ckfu.com" },
{ pattern = "22rkqi.com/*", zone_name = "22rkqi.com" },
{ pattern = "22sqyn.com/*", zone_name = "22sqyn.com" },
{ pattern = "2j8yf.com/*", zone_name = "2j8yf.com" },
{ pattern = "51biem.com/*", zone_name = "51biem.com" },
{ pattern = "51enwj.com/*", zone_name = "51enwj.com" },
{ pattern = "51mhwz.com/*", zone_name = "51mhwz.com" },
{ pattern = "51nfyx.com/*", zone_name = "51nfyx.com" },
{ pattern = "51noyp.com/*", zone_name = "51noyp.com" },
{ pattern = "51wbmt.com/*", zone_name = "51wbmt.com" },
{ pattern = "51wsib.com/*", zone_name = "51wsib.com" },
{ pattern = "5cdv.com/*", zone_name = "5cdv.com" },
{ pattern = "5fza.com/*", zone_name = "5fza.com" },
{ pattern = "5nzg.com/*", zone_name = "5nzg.com" },
{ pattern = "5o0f9.com/*", zone_name = "5o0f9.com" },
{ pattern = "6x272.com/*", zone_name = "6x272.com" },
{ pattern = "8jvt.com/*", zone_name = "8jvt.com" },
{ pattern = "8rfg.com/*", zone_name = "8rfg.com" },
{ pattern = "alfred-molina.com/*", zone_name = "alfred-molina.com" },
{ pattern = "beijinghanke.com/*", zone_name = "beijinghanke.com" },
{ pattern = "biqugex.biz/*", zone_name = "biqugex.biz" },
{ pattern = "biqugexx.biz/*", zone_name = "biqugexx.biz" },
{ pattern = "bqg5200.biz/*", zone_name = "bqg5200.biz" },
{ pattern = "christophermcdonald.info/*", zone_name = "christophermcdonald.info" },
{ pattern = "cinefilhd.org/*", zone_name = "cinefilhd.org" },
{ pattern = "cloud9roswell.com/*", zone_name = "cloud9roswell.com" },
{ pattern = "cnevol.com/*", zone_name = "cnevol.com" },
{ pattern = "codata2012.com/*", zone_name = "codata2012.com" },
{ pattern = "connectedmediaexperience.com/*", zone_name = "connectedmediaexperience.com" },
{ pattern = "cphya.com/*", zone_name = "cphya.com" },
{ pattern = "datokong.com/*", zone_name = "datokong.com" },
{ pattern = "gdstyj.net/*", zone_name = "gdstyj.net" },
{ pattern = "hdcafe.net/*", zone_name = "hdcafe.net" },
{ pattern = "ivhse.com/*", zone_name = "ivhse.com" },
{ pattern = "meimanle.com/*", zone_name = "meimanle.com" },
{ pattern = "nulcp.com/*", zone_name = "nulcp.com" },
{ pattern = "openpowerproject.org/*", zone_name = "openpowerproject.org" },
{ pattern = "othellowestend.com/*", zone_name = "othellowestend.com" },
{ pattern = "reformersclub.org/*", zone_name = "reformersclub.org" },
{ pattern = "resquework.org/*", zone_name = "resquework.org" },
{ pattern = "rz6lq.com/*", zone_name = "rz6lq.com" },
{ pattern = "samhuntingtononline.com/*", zone_name = "samhuntingtononline.com" },
{ pattern = "saudedoshmens.net/*", zone_name = "saudedoshmens.net" },
{ pattern = "spmdepej.net/*", zone_name = "spmdepej.net" },
{ pattern = "sponsorintell.com/*", zone_name = "sponsorintell.com" },
{ pattern = "steeljewelry168.com/*", zone_name = "steeljewelry168.com" },
{ pattern = "stevenwang.name/*", zone_name = "stevenwang.name" },
{ pattern = "sv-gtug.org/*", zone_name = "sv-gtug.org" },
{ pattern = "thisishull.net/*", zone_name = "thisishull.net" },
{ pattern = "troynightout.org/*", zone_name = "troynightout.org" },
{ pattern = "v7vpn.com/*", zone_name = "v7vpn.com" },
{ pattern = "wanbomanbet.net/*", zone_name = "wanbomanbet.net" },
{ pattern = "wangzhijuno.com/*", zone_name = "wangzhijuno.com" },
{ pattern = "westernweddingdresses.info/*", zone_name = "westernweddingdresses.info" },
{ pattern = "wfesg.com/*", zone_name = "wfesg.com" },
{ pattern = "wowpowerleveling8.com/*", zone_name = "wowpowerleveling8.com" }
]
