name = "12bet"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "5a4eb4d15f115821a3419fc0742096ee"
workers_dev = false
route = { pattern = "nnaoxiang.com/*", zone_name = "nnaoxiang.com" }