name = "multi"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
route = { pattern = "zhengguigongying.com/*", zone_name = "zhengguigongying.com" }
route = { pattern = "biggbosstamilvotings.com/*", zone_name = "biggbosstamilvotings.com" }
route = { pattern = "jiadacj.com/*", zone_name = "jiadacj.com" }
route = { pattern = "www.jieyangjiaolian.com/*", zone_name = "jieyangjiaolian.com" }
route = { pattern = "www.jinghuajiaoyu.com/*", zone_name = "jinghuajiaoyu.com" }
route = { pattern = "www.zjxfyb.com/*", zone_name = "zjxfyb.com" }
route = { pattern = "lkmtools.net/*", zone_name = "lkmtools.net" }
route = { pattern = "oulianpack.com/*", zone_name = "oulianpack.com" }
route = { pattern = "anhdmj.com/*", zone_name = "anhdmj.com" }
route = { pattern = "www.0718u.com/*", zone_name = "0718u.com" }
