name = "fun88y"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "101874e82d3ff354e72f3ff4e5894de2"
workers_dev = false
[placement]
mode = "smart"
routes = [ 
{ pattern = "11kxoc.com/*", zone_name = "11kxoc.com" },
{ pattern = "11msbu.com/*", zone_name = "11msbu.com" },
{ pattern = "11qyts.com/*", zone_name = "11qyts.com" },
{ pattern = "11thpm.com/*", zone_name = "11thpm.com" },
{ pattern = "22irde.com/*", zone_name = "22irde.com" },
{ pattern = "22vfpn.com/*", zone_name = "22vfpn.com" },
{ pattern = "51icrm.com/*", zone_name = "51icrm.com" },
{ pattern = "51ivnb.com/*", zone_name = "51ivnb.com" },
{ pattern = "51qzml.com/*", zone_name = "51qzml.com" },
{ pattern = "51sjmq.com/*", zone_name = "51sjmq.com" },
{ pattern = "52cdnt.com/*", zone_name = "52cdnt.com" },
{ pattern = "52dhjt.com/*", zone_name = "52dhjt.com" },
{ pattern = "52eifa.com/*", zone_name = "52eifa.com" },
{ pattern = "52fkre.com/*", zone_name = "52fkre.com" },
{ pattern = "52gjus.com/*", zone_name = "52gjus.com" },
{ pattern = "52hnam.com/*", zone_name = "52hnam.com" },
{ pattern = "52jtnc.com/*", zone_name = "52jtnc.com" },
{ pattern = "52jxzf.com/*", zone_name = "52jxzf.com" },
{ pattern = "52luwo.com/*", zone_name = "52luwo.com" },
{ pattern = "52nkwa.com/*", zone_name = "52nkwa.com" },
{ pattern = "52npsv.com/*", zone_name = "52npsv.com" },
{ pattern = "52quxb.com/*", zone_name = "52quxb.com" },
{ pattern = "52rmtk.com/*", zone_name = "52rmtk.com" },
{ pattern = "52rybp.com/*", zone_name = "52rybp.com" },
{ pattern = "52sech.com/*", zone_name = "52sech.com" },
{ pattern = "52vxah.com/*", zone_name = "52vxah.com" },
{ pattern = "52zrsv.com/*", zone_name = "52zrsv.com" },
{ pattern = "88abcw.com/*", zone_name = "88abcw.com" },
{ pattern = "88ahcm.com/*", zone_name = "88ahcm.com" },
{ pattern = "88bhqf.com/*", zone_name = "88bhqf.com" },
{ pattern = "88cbhz.com/*", zone_name = "88cbhz.com" },
{ pattern = "88djnb.com/*", zone_name = "88djnb.com" },
{ pattern = "88figa.com/*", zone_name = "88figa.com" },
{ pattern = "88hqpn.com/*", zone_name = "88hqpn.com" },
{ pattern = "88ksde.com/*", zone_name = "88ksde.com" },
{ pattern = "88lwnu.com/*", zone_name = "88lwnu.com" },
{ pattern = "88lybc.com/*", zone_name = "88lybc.com" },
{ pattern = "88nxof.com/*", zone_name = "88nxof.com" },
{ pattern = "88nzfi.com/*", zone_name = "88nzfi.com" },
{ pattern = "88tigq.com/*", zone_name = "88tigq.com" },
{ pattern = "88vqgd.com/*", zone_name = "88vqgd.com" },
{ pattern = "attributionnoncommercialsharealiketv.com/*", zone_name = "attributionnoncommercialsharealiketv.com" },
{ pattern = "copyrightcamp.org/*", zone_name = "copyrightcamp.org" },
{ pattern = "creativecmomons.org/*", zone_name = "creativecmomons.org" },
{ pattern = "gdgschaumburg.com/*", zone_name = "gdgschaumburg.com" },
{ pattern = "icetgreencar.org/*", zone_name = "icetgreencar.org" },
{ pattern = "szfit.net/*", zone_name = "szfit.net" },
{ pattern = "vztug8.com/*", zone_name = "vztug8.com" }
]
